package co.song.prj;

import co.song.prj.Member;
import java.util.List;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Wed Aug 04 14:21:50 KST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Wed Aug 04 14:21:50 KST 2021
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Wed Aug 04 14:21:50 KST 2021
     */
    Member selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Wed Aug 04 14:21:50 KST 2021
     */
    List<Member> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEMBER
     *
     * @mbg.generated Wed Aug 04 14:21:50 KST 2021
     */
    int updateByPrimaryKey(Member record);
}